### ISSUE TITLE
core: support multiple knowledge base

### ISSUE THREAD

**Issue by sykp241095** [pingcap/autoflow#327]
### Description

- `chunks_{knowledge_base_id}`
- `entities_{knowledge_base_id}`
- `relationships_{knowledge_base_id}`

### TODO

- [x] Introduce "knowledge base" concept to manage and isolate documents from different domain (https://github.com/pingcap/tidb.ai/pull/366)
- [x] Support configure embedding model on knowledge base level (when created KB)
- [x] Support multiple knowledge base retrivel on chat engine
- [x] Support link multiple datasource to one knowledge base
- [x] Add "Knowledge Bases" UI @634750802 #370 #408 
  - [x] A list page to show knowledge bases (maybe using card list ui is better than table ui)
  - [x] A dialog to create new knowledge base (configure name, description and datasources)
  - [x] A documents list page to manage documents (move document list page into it) 
  - [x] A setting page to configure name, description and index config (vector index / knowledge graph index / full text index)
- [x] Migrate Index Process Page to knowledge base level @634750802 
- [x] Knowledge Base related Open API
- [ ] Support knowledge base level permission control (Feature Plan)
- [ ] Support change embedding model and reindex the documents (Feature Plan)
